Added notice buttons based on tags and added demo folder
shopgate-professional-services/ext-redirect-non-app-item-purchase pull request #1
Opened 2020-03-10 18:31 UTC by dqdquint

Tested with shop no: 31866 and set targetTag config to gs24. 
Example item with gs24 is "product with two tags"
Example item without gs24 is "1776 Flag Full Zip Hoodie"

2020-03-11 18:06 UTC, aaron-martin requested changes
I think it makes sense to support having more than one triggering tag. I think it makes sense to also support triggering product properties. I think it makes sense to support actions other than just linking to a phone call.

2020-03-18 08:40 UTC, Carsten89 requested changes

2020-03-18 08:40 UTC, Carsten89 commented on README.md
> +  "barFontColor": "whit"
```suggestion
  "barFontColor": "white"
```

2020-03-18 08:40 UTC, Carsten89 commented on demo/index.md
> +  "contactNumber": "123-456-7890",
outdated. --> purchaseRedirectHref

2020-03-18 08:40 UTC, Carsten89 commented on README.md
> +contactNumber
outdated --> purchaseRedirectHref

2020-03-18 08:40 UTC, Carsten89 commented on README.md
>  Will prevent items with a given tag from being added to cart. A notice to call merchant will be displayed.
..tag or property...

2020-03-18 10:54 UTC, aaron-martin commented on README.md
> +  "barFontColor": "whit"
done

2020-03-18 10:57 UTC, aaron-martin commented on demo/index.md
> +  "contactNumber": "123-456-7890",
done

2020-03-18 10:57 UTC, aaron-martin commented on README.md
> +contactNumber
done

2020-03-18 10:59 UTC, aaron-martin commented on README.md
>  Will prevent items with a given tag from being added to cart. A notice to call merchant will be displayed.
done

2020-03-18 11:00 UTC, aaron-martin commented on README.md
>  Will prevent items with a given tag from being added to cart. A notice to call merchant will be displayed.
done

2020-03-18 11:10 UTC, Carsten89 approved these changes

2020-03-18 11:16 UTC, merged